third_lines = {'NN': [(['PRP', 'MD', 'VB', 'TO', 'DT', 'NN'], ['he', 'would', 'go', 'to', 'a', 'party']), 
        (['VBN', 'IN', 'DT', 'NN'], ['collapsed', 'from', 'the', 'strain']), 
        (['PRP', 'VBD', ',', 'IN', 'DT', 'NN'], ['he', 'said', ',', 'with', 'a', 'sigh']), 
        (['PRP', 'VBD', 'IN', 'PRP$', 'NN'], ['he', 'bought', 'for', 'his', 'daughter']), 
        (['PRP', 'VBD', 'RP', 'CD', 'NN'], ['she', 'set', 'out', 'one', 'day']), 
        (['WHEN', 'DT', 'NN', 'VBZ', 'PRP$', 'NN'], ['when', 'a', 'dame', 'wears', 'my', 'coat']), 
        (['DT', 'NN', 'IN', 'DT', 'NN'], ['a', 'fish', 'with', 'a', 'grin']), 
        (['VBD', 'DT', 'CD', 'TO', 'DT', 'NN'], ['said', 'the', 'two', 'to', 'the', 'tutor']), 
        (['PDT', 'DT', 'NNS', 'VBD', 'IN'], ['all', 'the', 'flowers', 'looked', 'around']), 
        (['RB', 'DT', 'NN'], ['of course', 'the', 'expense']), 
        (['VBD', 'DT', 'NN', 'IN', 'DT', 'NN'], ['said', 'the', 'man', 'at', 'the', 'door']), 
        (['VBD', 'DT', 'NN', ',', 'DT', 'NN'], ['had', 'a', 'quarrel', ',', 'no', 'doubt']), 
        (['CC', 'PRP$', 'NN', ',', 'VBN', 'NN'], ['but', 'his', 'daughter', ',', 'named', 'nan']), 
        (['PRP', 'VBD', 'RB', 'IN', 'DT', 'NN'], ['they', 'came', 'back', 'from', 'the', 'ride']), 
        (['IN', 'VBG', 'PRP$', 'NN'], ['after', 'croaking', 'his', 'wife']), 
        (['IN', 'NN'], ['in spite of', 'advice']), 
        (['DT', 'NN', 'VBN', 'NN'], ['a', 'widow', 'named', 'block']), 
        (['CC', 'IN', 'PRP$', 'NN'], ['and', 'as for', 'my', 'hair']), 
        (['PRP', 'VBD', 'DT', 'NN'], ['he', 'indulged', 'a', 'desire']), 
        (['IN', 'PRP$', 'JJ', 'NN'], ['since', 'her', 'apple-cheeked', 'groom']), 
        (['VBD', 'PRP', 'IN', 'WP', 'DT', 'NN'], ['switched', 'it', 'on', 'what', 'a', 'din']), 
        (['DT', 'NN', 'IN', 'PRP$', 'NN'], ['the', 'cause', 'of', 'his', 'sorrow']), 
        (['CD', 'NNS', 'CC', 'DT', 'NN'], ['two', 'owls', 'and', 'a', 'hen']), 
        (['IN', 'PRP$', 'NN', 'IN', 'NN'], ['in', 'my', 'pocket', 'for', 'cash']), 
        (['IN', 'JJ', 'NN'], ['due to', 'up-to-date', 'science']), 
        (['WHEN', 'DT', 'NN', 'VBZ', 'PRP$', 'NN'], ['when', 'a', 'girl', 'wears', 'my', 'coat']), 
        (['THAN', 'DT', 'NN', 'IN', 'NN'], ['than', 'a', 'goulash', 'of', 'rat']), 
        (['PRP', 'VBP', 'DT', 'NN', 'NN'], ['you', 'are', 'a', 'simpleton', 'loon']), 
        (['PRP', 'VBD', 'IN', 'DT', 'NN'], ['it', 'said', 'on', 'the', 'door']), 
        (['VBN', 'TO', 'DT', 'NN'], ['collapsed', 'to', 'the', 'ground']), 
        (['MD', 'RB', 'VB', 'RP', 'TO', 'NN'], ["'did", "not", 'rush', 'off', 'to', 'town']), 
        (['PRP', 'MD', 'VBN', 'VBN', 'IN', 'DT', 'NN'], ['they', "had", 'been', 'laid', 'on', 'a', 'chair']),
        (['EX', 'VBZ', 'NN', 'IN', 'DT', 'NN'], ['there', "was", 'nothing', 'like', 'a', 'food'])], 
 'MD': [(['DT', 'NN', 'MD', 'VB'], ['a', 'canner', 'can', 'can'])], 
 '.': [(['WHEN', 'VBN', ',', 'WP', 'VBZ', 'JJ', '.'], ['when', 'asked', ',', 'who', 'is', 'dead', '?']), 
       (['VBD', 'DT', 'NN', ',', 'VB', 'PRP', 'VB', '.'], ['said', 'the', 'fly', ',', 'let', 'us', 'flee', '!']), 
       (['VB', 'PRP', 'NN', 'CC', 'NN', '.'], ['have', 'you', 'needle', 'and', 'thread', '?']), 
       (['CC', 'VBD', ',', 'FW', ',', 'MD', 'PRP', 'VB', '.'], ['and', 'said', ',', 'miss', ',', 'can', 'we', 'dance', '?']),
       (['WHEN', 'VBN', ',', 'WRB', 'SO', 'JJ', '.'], ['when', 'asked', ',', "'why", 'so', 'blue', '?'])], 
 'PRP': [(['RB', 'DT', 'JJ', 'NN', 'VBD', 'PRP'], ['soon', 'a', 'happy', 'thought', 'hit', 'her'])], 
 'VB': [(['PRP', 'VBD', 'CD', 'TO', 'NN'], ['she', 'gave', 'one', 'to', 'adam']), 
        (['VBD', 'DT', 'NN', ',', 'VB', 'PRP', 'VB'], ['said', 'the', 'fly', ',', 'let', 'us', 'flee']), 
        (['VBD', 'DT', 'NN', ',', 'VB', 'RB', 'VB'], ['said', 'the', 'waiter', ',', 'do', "not", 'shout'])], 
 'VBD': [(['CC', 'DT', 'NN', 'PRP', 'VBD'], ['but', 'the', 'copy', 'he', 'wrote']), 
         (['CC', 'JJ', ',', 'CC', 'JJ'], ['and', 'flat', ',', 'and', 'compressed']), 
         (['IN', 'WHEN', 'PRP', 'VBD'], ['that', 'when', 'she', 'assayed']), 
         (['PRP', 'RB', 'VBD'], ['he', 'gladly', 'proclaimed']), 
         (['WHILE', 'PRP$', 'NN', 'VBD'], ['while', 'her', 'lover', 'lamented']), 
         (['CC', 'VBN', ',', 'PRP', 'VBD'], ['but', 'shaken', ',', 'he', 'shot']), 
         (['IN', 'DT', 'NNS', 'IN', 'PRP', 'VBD'], ["'til", 'the', 'salts', 'that', 'she', 'shook']), 
         (['DT', 'WHEN', 'PRP', 'VBD'], ['that', 'when', 'he', 'essayed'])], 
 'NNS': [(['PRP', 'VBD', ',', 'RB', 'VBD'], ['she', 'ran', ',', 'almost', 'flew']), 
         (['IN', 'PRP$', 'NNS', 'IN', 'DT', 'NNS'], ['with', 'your', 'toes', 'on', 'the', 'keys']), 
         (['IN', 'DT', 'NNS', '.', 'IF', 'JJ'], ['at', 'the', 'movies', '?', 'if', 'yes']), 
         (['IN', 'PRP$', 'NN', ',', 'PRP$', 'NNS'], ['from', 'your', 'offspring', ',', 'my', 'dears'])], 
 'JJ': [(['PRP$', 'NNS', 'VBD', 'SO', 'JJ'], ['her', 'thanks', 'were', 'so', 'cold']), 
        (['SO', 'JJ', 'CC', 'JJ'], ['so', 'exclusive', 'and', 'few']), 
        (['PRP', 'IN', 'VBD', 'SO', 'JJ'], ['it', 'at last', 'grew', 'so', 'small']), 
        (['DT', 'NN', 'VBD', ',', 'RB', 'JJ'], ['the', 'teacher', 'said', ',', 'not', 'right']), 
        (['IN', 'DT', 'NN', 'VBZ', 'DT', 'JJ'], ['for', 'the', 'pattern', "is", 'all', 'wrong']), 
        (['CC', 'DT', 'CD', 'VBD', 'JJ'], ['but', 'this', 'one', 'was', 'easy']), 
        (['PRP', 'VBZ', 'CC', 'JJ'], ['it', 'expresses', 'but', 'nought'])], 
 'VBN': [(['AS', 'NN', 'WDT', 'VBZ', 'VBN'], ['as', 'spacetime', 'that', "is", 'curved']), 
         (['CC', 'WHEN', 'PRP', 'VBP', 'VBN'], ['but', 'when', 'I', 'have', 'dough']), 
         (['IN', 'PRP$', 'NNS', 'VBN'], ['because', 'its', 'feet', 'stuck'])], 
 'VBG': [(['CC', 'PRP', 'VBD', 'VBG'], ['but', 'she', 'started', 'absorbing'])], 
 'DT': [(['PRP', 'MD', 'VB', 'EX', 'VBP', 'DT'], ['I', 'could', 'swear', 'there', 'are', 'some'])], 
 'RB': [(['RBR', 'JJ', 'IN', 'IN', 'RB'], ['more', 'bizarre', 'though', 'by', 'far'])], 
 'SO': [(['WHEN', 'VBD', 'DT', 'VBD', 'SO'], ['when', 'told', 'this', 'was', 'so'])]}
